version: "3.8"
services:
  movies:
    image: rahamshaik/moviespaytmrepoo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3

  train:
    image: rahamshaik/trainpaytmrepo0:latest
    ports:
      - 82:80
    deploy:
      replicas: 3

  dth:
    image: rahamshaik/dthpaytmrepoo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3

  recharge:
    image: rahamshaik/rechargepaytmrepo0:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
