version: '3.8'
services:
  movies:
    image: abdulrazig/ptmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: abdulrazig/ptmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: abdulrazig/ptmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: abdulrazig/ptmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

